drone_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from drone_inventory.forms import UserLoginForm
#auth gets imported to __init__, and then app.register_blueprint(auth) so these routes can be used
auth = Blueprint('auth', __name__, template_folder='auth_templates')

#after we set up database/db.session
from drone_inventory.models import  User, db, check_password_hash

#Imports for flask login
from flask_login import login_user, logout_user, login_required


@auth.route('/signup', methods=['GET','POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)


            #do this after establishing database
            user = User(email, password = password)
            #create interface between database and user model
            #like an insert statement/session
            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'user-created')

            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form Inputs')
    return render_template('signup.html', form = form)

@auth.route('/signin', methods=['GET','POST'])
def signin():
    form = UserLoginForm()

    #try to get info and validate the form, if it isnt found - give error
    try:
        #checks if the request from form submission is set to 'POST' and form is validated
        if request.method == 'POST' and form.validate_on_submit():
            #set variables equal to values entered into signin form
            email = form.email.data
            password = form.password.data
            #print lets us know these things are getting pulled correctly, helps error checking/finding
            print(email,password)

            #we want to filter by the email provided by the form (defined above)
            #.first() asks for first value that comes back under this query
            logged_user = User.query.filter(User.email == email).first()

            #want to check password and currently logged user
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in: via email/password', 'auth-success')
                return redirect(url_for('site.home'))
            else:
                flash('Your email/password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form!')
    
    #pass the form = UserLoginForm() to return statement
    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

drone_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required
#site gets imported to __init__, and then app.register_blueprint(site) so these routes can be used
site = Blueprint('site', __name__, template_folder='site_templates')
"""
Blueprint Configuration 
-The first argument ('site'), is the Blueprint's name, which is used by
Flask's routing system
-Second argument (__name__) is the Blueprint's import name, which Flask uses
to locate the Blueprint resources. 
-Last argument (template_folder) is the Blueprint's HTML template folder, which
tells the Blueprint which HTML files to use for specific routes
"""

#creating a route
@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

drone_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Title</title>
</head>
<body>
    <!--Navbar here-->
    <nav class="ct-nav">
        <div>
            <img src="../static/images/Coding Drones Logo.png" alt="Coding Drones Logo">
        </div>
        <!--Nav Items-->
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>The Coding Drones Inventory Project</li>
                </a>
                <a href="">
                    <li>Donate Here</li>
                </a>
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>
                
                
                <!--User Auth Check for sign-in/sign-out button showing-->
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('auth.logout') }}">
                    <li>Log Out</li>
                </a>

                    
                {% else %}
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up</li>
                </a>                
                {% endif %}



            </ul>
        </div>
    </nav>

    {% block content %}  
    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.4/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.min.js"></script>
</body>
</html>

drone_inventory/templates/form.html
<!--HTML Produced By the Flask Form-->

<form method="POST">
    {{ form.hidden_tag() }} <!--SECRET KEY from config we need to have to make it a valid form-->
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = "Place Email Here") }} <!--Calls form function and allows us to add verbosity-->
        </fieldset>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = 'form-control', placeholder = "Place Pasword Here") }}
        </fieldset>

        <!--Submit button-->
        {{ form.submit_button(class = 'btn btn-primary') }}
    </div>
</form>